name: Deploy Spring Boot to AWS EC2

on:
  push:
    branches:
      - main # Chạy khi push lên `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Upload JAR to S3
        run: |
          aws s3 cp target/spring-boot-2-hello-world-1.0.2-SNAPSHOT.jar s3://hoatruong-bucket/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          aws s3 cp s3://hoatruong-bucket/spring-boot-2-hello-world-1.0.2-SNAPSHOT.jar /home/ec2-user/
          sudo systemctl restart my-spring-boot-app
          EOF
