name: Deploy Spring Boot to AWS EC2

on:
  push:
    branches:
      - main # Chạy khi có thay đổi trên nhánh `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Bước 3: Build file Spring Boot JAR
      - name: Build Spring Boot JAR
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      # Bước 4: Upload file JAR lên S3
      - name: Upload JAR to S3
        run: |
          aws s3 cp target/spring-boot-2-hello-world-1.0.2-SNAPSHOT.jar s3://hoatruong-bucket/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'

      # Bước 5: Deploy lên EC2
      - name: Deploy to EC2
        run: |
          # Tạo thư mục SSH
          mkdir -p ~/.ssh

          # Lưu SSH_PRIVATE_KEY từ Secrets vào file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          # Cấp quyền bảo mật cho file Private Key
          chmod 600 ~/.ssh/id_rsa

          # Thêm Public IP của EC2 vào danh sách known_hosts
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
            # Kiểm tra và dừng tiến trình chiếm port 8080
            sudo fuser -k 8080/tcp || true

            # Tải file JAR từ S3
            aws s3 cp s3://hoatruong-bucket/spring-boot-2-hello-world-1.0.2-SNAPSHOT.jar /home/ec2-user/

            # Restart service
            sudo systemctl restart my-spring-boot-app
          EOF
